# Generated by Django 4.2.5 on 2023-09-17 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('title_accommodation', models.CharField(max_length=300, verbose_name='Проживание')),
                ('description_accommodation', models.TextField(blank=True)),
                ('comfort', models.CharField(choices=[('Base', 'Базовый'), ('Simple', 'Простой'), ('Medium', 'Средний'), ('luxury', 'Люкс'), ('Premium', 'Премиум')], max_length=13, verbose_name='Степень комфорта')),
                ('type', models.CharField(choices=[('Tent', 'Палатка'), ('Hostel', 'Гостиница'), ('Hotel', 'Отель'), ('Cottage', 'Котедж')], max_length=7, verbose_name='Тип проживания')),
                ('slug', models.SlugField(blank=True, max_length=120, primary_key=True, serialize=False)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='tour.tour')),
            ],
            options={
                'verbose_name': 'Проживание',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('title_hotel', models.CharField(max_length=100, verbose_name='Название отеля')),
                ('description_hotel', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=120, primary_key=True, serialize=False)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='accommodation.accommodation')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='HotelImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_images')),
                ('hotel', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='accommodation.hotel')),
            ],
        ),
    ]
